#!/bin/zsh

# list the files and directories of the current directory.
# Ignore the hidden files, the "." and the "..".
# Separate the results with commas only.
# Order them by ascending order of access time (the newest first).
# Have the directories ends with a /. 


ls -tpm